### ISSUE TITLE
I tried to docker-compose up -d --build 

### ISSUE THREAD

**Issue by davidporter** [cadmiumkitty/dcaf-2020-provo#1] opened 2021-09-15 02:27 UTC
I tried to docker-compose up -d --build  and got the following error:

`PS S:\src\dcaf-2020-provo> docker-compose up -d --build
Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "docker\transport\npipeconn.py", line 32, in connect
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 200, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[7760] Failed to execute script docker-compose`

Any chance you can help me resolve and or point me to a similar project this is exactly what I've been looking for.

**Comment by cadmiumkitty** [comment] 2021-09-15 07:33
Hi David,

Struggling to reproduce this exact error, so wondering if this is all you see in the shell? Are you running docker-compose from the directory you cloned the repository to?

Tried reproducing it, and there were other issues as demo took place more than one and a half years ago and products used in it, such as Jena, moved on in terms of versions. Also, instructions were a bit simplistic as you need to build two individual Java projects (repo and connect) first.

Committed the changes to Jena container, docker-compose.yml and the README and checked that it is running fine - try and give it another go.

Could you share more details of what you are looking for as demo covered plenty of ground? Are you after Kafka SPARQL sink, PROV visualization, PROV set up specifically for repo agreements, or something else?

**Comment by davidporter** [comment] 2021-09-22 19:14
Thank you for the reply.
I tried again and got further but errored out on building Jena:
```
PS S:\src\dcaf-2020-provo> docker-compose up -d --build
Building provoviz
[+] Building 1.0s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                                                              0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                                                                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:2.7-buster                                                                                                                                                                                                                                                                                                                              0.8s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                                                                                                                                                                                                                                                     0.0s
 => [1/4] FROM docker.io/library/python:2.7-buster@sha256:d8fac68ebdc45b8d66d53f1ed6c1532da81109a8f5532a6ca0c951ed31107d70                                                                                                                                                                                                                                                                        0.0s
 => CACHED [2/4] RUN git clone https://github.com/cadmiumkitty/provoviz.git                                                                                                                                                                                                                                                                                                                       0.0s
 => CACHED [3/4] RUN pip install -r /provoviz/requirements.txt                                                                                                                                                                                                                                                                                                                                    0.0s
 => CACHED [4/4] WORKDIR /provoviz/src                                                                                                                                                                                                                                                                                                                                                            0.0s
 => exporting to image                                                                                                                                                                                                                                                                                                                                                                            0.1s
 => => exporting layers                                                                                                                                                                                                                                                                                                                                                                           0.0s
 => => writing image sha256:ed6486b2cb862ef43a6db517c0c37678046512fcc8a9d1f28d7162b92fcc010c                                                                                                                                                                                                                                                                                                      0.0s
 => => naming to docker.io/library/provoviz                                                                                                                                                                                                                                                                                                                                                       0.0s
Building repo
[+] Building 0.9s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                                                              0.0s
 => => transferring dockerfile: 31B                                                                                                                                                                                                                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/openjdk:13                                                                                                                                                                                                                                                                                                                                     0.6s
 => [auth] library/openjdk:pull token for registry-1.docker.io                                                                                                                                                                                                                                                                                                                                    0.0s
 => [internal] load build context                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 80B                                                                                                                                                                                                                                                                                                                                                                  0.0s
 => [1/2] FROM docker.io/library/openjdk:13@sha256:08ab736e5b08665c76dc8b16d8b06e42fca5a065e1203229bf39af71c2605d83                                                                                                                                                                                                                                                                               0.0s
 => CACHED [2/2] ADD target/repo-0.0.1-SNAPSHOT.jar /                                                                                                                                                                                                                                                                                                                                             0.0s
 => exporting to image                                                                                                                                                                                                                                                                                                                                                                            0.0s
 => => exporting layers                                                                                                                                                                                                                                                                                                                                                                           0.0s
 => => writing image sha256:e0c40c4041c1d7bc8cd456d9fad66486d789fef23669eb1cb697d93c78c8e03c                                                                                                                                                                                                                                                                                                      0.0s
 => => naming to docker.io/library/repo                                                                                                                                                                                                                                                                                                                                                           0.0s
Building connect
[+] Building 0.9s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                                                              0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                                                                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/wurstmeister/kafka:2.12-2.4.0                                                                                                                                                                                                                                                                                                                          0.7s
 => [auth] wurstmeister/kafka:pull token for registry-1.docker.io                                                                                                                                                                                                                                                                                                                                 0.0s
 => [1/4] FROM docker.io/wurstmeister/kafka:2.12-2.4.0@sha256:47bb92ce7ff3d5829a0f02ddd7ab1d13ebd6c71db445576a4998d07cf1c309da                                                                                                                                                                                                                                                                    0.0s
 => [internal] load build context                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 205B                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => CACHED [2/4] COPY ./connect-standalone.properties /opt/kafka/config/connect-standalone.properties                                                                                                                                                                                                                                                                                             0.0s
 => CACHED [3/4] COPY ./connect-sparql-sink.properties /opt/kafka/config/connect-sparql-sink.properties                                                                                                                                                                                                                                                                                           0.0s
 => CACHED [4/4] COPY ./target/connect-sparql-sink-0.0.1-SNAPSHOT-standalone.jar /kafka-connect-sparql/connect-sparql-sink-0.0.1-SNAPSHOT-standalone.jar                                                                                                                                                                                                                                          0.0s
 => exporting to image                                                                                                                                                                                                                                                                                                                                                                            0.0s
 => => exporting layers                                                                                                                                                                                                                                                                                                                                                                           0.0s
 => => writing image sha256:c133acb724277cb764c692e3bad730e6e798828a25a3145ad91685d178083e18                                                                                                                                                                                                                                                                                                      0.0s
 => => naming to docker.io/library/connect                                                                                                                                                                                                                                                                                                                                                        0.0s
Building fuseki
[+] Building 0.8s (7/11)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                                                              0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                                                                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/openjdk:13                                                                                                                                                                                                                                                                                                                                     0.2s
 => [1/7] FROM docker.io/library/openjdk:13@sha256:08ab736e5b08665c76dc8b16d8b06e42fca5a065e1203229bf39af71c2605d83                                                                                                                                                                                                                                                                               0.0s
 => [internal] load build context                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 31B                                                                                                                                                                                                                                                                                                                                                                  0.0s
 => CACHED [2/7] RUN curl https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-4.1.0.tar.gz -o ./apache-jena-fuseki-4.1.0.tar.gz                                                                                                                                                                                                                                                             0.0s
 => ERROR [3/7] RUN tar xvzf apache-jena-fuseki-4.1.0.tar.gz                                                                                                                                                                                                                                                                                                                                      0.5s
------
 > [3/7] RUN tar xvzf apache-jena-fuseki-4.1.0.tar.gz:
#6 0.449
#6 0.449 gzip: stdin: not in gzip format
#6 0.450 tar: Child returned status 1
#6 0.450 tar: Error is not recoverable: exiting now
------
executor failed running [/bin/sh -c tar xvzf apache-jena-fuseki-4.1.0.tar.gz]: exit code: 2
ERROR: Service 'fuseki' failed to build : Build failed
```

I looked online but could not find a solution.  I am mostly interested in the overall architecture of getting provenance data from running processes in to Jena.  I greatly appreciate any help you can provide.

**Comment by davidporter** [comment] 2021-09-22 19:20
I looked in to the jena-fuseki Dockerfile and found that:
Line 4:
RUN curl https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-4.1.0.tar.gz -o ./apache-jena-fuseki-4.1.0.tar.gz
could not find the link:
https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-4.1.0.tar.gz
I'm not sure how to correct this?

**Comment by cadmiumkitty** [comment] 2021-09-22 19:45
Ah, Jena released 4.2.0 since I wrote my response - you need to use https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-4.2.0.tar.gz instead. I just pushed the change - try again and see if you get any further?

**Comment by davidporter** [comment] 2021-09-23 01:56
Cool! That fixed it.  I am running now and seeing the Jena RDF data grow as the containers are running.

**Comment by cadmiumkitty** [comment] 2021-09-23 07:19
Great, I'll close the issue then. I see you had a question about the overall architecture - in case you have not seen it, take a look at slide 18 of the original slide deck for the talk at https://www.slideshare.net/EugeneMorozov/data-provenance-and-prov-ontology.

**Closed as completed by cadmiumkitty** 2021-09-23 07:19 UTC
